### ISSUE TITLE
RAW Image preview is wrong

### ISSUE THREAD

**Issue by svatas** [CyberTimon/RapidRAW#317]
I am using 1.3.12 in Linux (Tuxedo OS on KDE Plasma 6 and Wayland). I have a folder with RAW images from my Sony A7 III (arw).

Step 1: When I see the folder I can see rigth amount of images in there, but preview images are for some of them completely wrong.

<img width="2696" height="1515" alt="Image" src="https://github.com/user-attachments/assets/8b362f36-4fbb-4a6b-b59d-bcf9317c3a11" />

The images 1, 5 and 6 shows the same goat I shooted when visited ZOO with kids. But in this folder you can see some illustrative images to some technical article, so there is a charger and some light taken with various camera settings. No goat shooted.

Step 2: I just switched to the folder and you can see, that preview image and the image was refreshed to the proper one, so image 1 is refreshed, but images 5 and 6 are still wrong.

<img width="2696" height="1515" alt="Image" src="https://github.com/user-attachments/assets/6ac8e8dc-5ec0-4bd1-bfeb-dc7c2a24a010" />

Step 3: same efect for image 5, preview and image refreshed and replaced by the proper one

<img width="2696" height="1515" alt="Image" src="https://github.com/user-attachments/assets/00031235-dd5e-4489-8bed-50e08ea21c62" />

Step 4: When I was quick, I can see even the wrong image and preview as I click on the image 6. For some time, until refreshed, image is there.

<img width="2696" height="1515" alt="Image" src="https://github.com/user-attachments/assets/22b62793-b1e3-4b29-9a8a-45fb3865628b" />

Step 5: Image refreshed and replaced with proper one.

<img width="2696" height="1515" alt="Image" src="https://github.com/user-attachments/assets/5461c3bd-cec6-44fb-b7d6-de5c0693b8d3" />

Step 6: In folder view everything is updatedto proper images.

<img width="2696" height="1515" alt="Image" src="https://github.com/user-attachments/assets/b0f9770f-ec7a-4319-a4cc-f3a19a829519" />

For me this looks like some refresh/update process "failure" as it is initiated when the image is previewed. So functionality is there but the trigger for update is somehow wrong.

**Comment by CyberTimon** [comment]
Okay this is very strange. Can't reproduce and never happend on any system I'm aware off. But thank you for reporting.

Might be related: https://github.com/CyberTimon/RapidRAW/issues/306

Have you tried to launch RapidRAW with following commands?

```bash
WEBKIT_DISABLE_DMABUF_RENDERER=1 rapidraw
```
or
```bash
WEBKIT_DISABLE_COMPOSITING_MODE=1 rapidraw
```

**Comment by CyberTimon** [comment]
Maybe fixed here: https://github.com/CyberTimon/RapidRAW/commit/84b5395e05adb97648398eacf343cdbae2663674

**Comment by william-sy** [comment]
@svatas Can you update, and report back if its still a problem ? else please close the issue.

**Comment by svatas** [comment]
@william-sy To answer your question - I must report - even in 1.3.13 : bug is still present

**Comment by william-sy** [comment]
You can be unhappy about it, But yes every once in a while else tickets will go stale. And how to know if some one needs to work on it if its for example a 6 month old issue. 

So small effort to update your ticket once in a while.

**Comment by william-sy** [comment]
@svatas, I see the ticket marked as invalid By the maintainer. 

But 
1: is it only in this folder? 
2: If you open a new session/folder from the home page is it still the same problem
3: if you go to the settings on the home page an clean the cache and go back to continue session, is it still there ?

**Comment by svatas** [comment]
To answer your questions:
1. No, it is i all folders I have connected.
2. Yes, does not matter which folder and which way I choose (new session etc.)
3. Yes, I tried to delete completely the cache. The problem is there. When I click to the picture, the image preview is not correct but when it is generated (by clicking on it) it is there and is correct. The loop will start when I clean the cache and the image preview is not regenerated. So the process of generating preview is correct but it is not correctly initiated for some pictures, now the trigger is to click and open the image. And the preview is there until I clean the cache.

**Comment by william-sy** [comment]
Thanks for the reply, Lets wait for https://github.com/CyberTimon/RapidRAW/pull/347 as it revamps file loading and handling.
It should be there in 1.4.0 so it might or might not be fixed with it.

**Comment by william-sy** [comment]
@svatas 1.4.1 is out there has been some major rework on image loading. 
Extra question: Do you have any cropping on the images ?

**Comment by svatas** [comment]
I can confirm, that in 1.4.1 this bug is not present anymore. You can close this as solved.

**Comment by william-sy** [comment]
Thanks please close the ticket
