### ISSUE TITLE
AI mask issue on Mac M2

### ISSUE THREAD

**Issue by nessie710** [CyberTimon/RapidRAW#93]
I think there is something wrong with the installation on Mac m2. When I try to create a mask either with the subject detection or with the foreground tool it throws an error. 

> AI mask failed: failed to create ONNX Runtime session
> Modelproto does not have a graph

I could not find a solution by myself, but maybe it's just something I am not aware of.

**Comment by CyberTimon** [comment]
Which version of python is your system running?

It's probably related to this: https://github.com/microsoft/onnxruntime/issues/9755

**Comment by nessie710** [comment]
I have versione 3.12.7
I found that thread too, but I don't know how to solve the problem. Maybe I should upgrade the version? Indeed your project is very new

**Comment by dernikolas** [comment]
Problem also exist under Linux (CachyOS, KDE Plasma)

**Comment by nessie710** [comment]
I might add also that the brush tool in the mask section is not as large as it's previewed. I attach some examples.

<img width="1516" height="965" alt="Image" src="https://github.com/user-attachments/assets/c9b9a552-d67e-4627-beb7-d22eca4b832c" />
<img width="1516" height="965" alt="Image" src="https://github.com/user-attachments/assets/fe1b3898-8c6c-4934-b957-1b23ecb1fe1e" />

**Comment by CyberTimon** [comment]
I will try to adress these issues on the weekend. Might not be able to fix the "Modelproto does not have a graph" error but the others should be quite easy to fix.

**Comment by CyberTimon** [comment]
Brush size issue is solved: https://github.com/CyberTimon/RapidRAW/commit/9026575e8d2546bc4060f5ebbd6bbeb3a80f5dd7

**Comment by dernikolas** [comment]
Error is still there

<img width="960" height="447" alt="Image" src="https://github.com/user-attachments/assets/1aaae540-ca25-413b-a9be-5f9b56982f09" />

**Comment by CyberTimon** [comment]
That's expected. I couldn't find a fix for it yet.

**Comment by CyberTimon** [comment]
Probably fixed now since I migrated to ORT V2. If the issue still happens, feel free to reopen :)
